============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/runner/work/rich/rich
configfile: pyproject.toml
plugins: cov-5.0.0
collected 0 items
WARNING: Failed to generate report: No data to report.



---------- coverage: platform linux, python 3.8.18-final-0 -----------

============================ no tests ran in 0.03s =============================
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/runner/work/rich/rich
configfile: pyproject.toml
plugins: cov-5.0.0
collected 0 items / 1 error
WARNING: Failed to generate report: No data to report.


==================================== ERRORS ====================================
____________ ERROR collecting generated_tests/python/test_color.py _____________
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/pathlib.py:582: in import_path
    importlib.import_module(module_name)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:175: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:355: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/ast.py:47: in parse
    return compile(source, filename, mode, flags,
E     File "/home/runner/work/rich/rich/generated_tests/python/test_color.py", line 135
E       ```
E       ^
E   SyntaxError: invalid syntax

---------- coverage: platform linux, python 3.8.18-final-0 -----------

=========================== short test summary info ============================
ERROR generated_tests/python/test_color.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.28s ===============================
